
services:
  db:
    image: postgres:15
    container_name: tiendadb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSRGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data